version: '3.8'
services:
######################################################################################
  web:
    container_name: ${DJANGO_PROJECT_NAME}_web
    image: ${DJANGO_PROJECT_NAME}_web
    build:
      context: ./${DJANGO_PROJECT_NAME}
      dockerfile: ./dockerfiles/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./${DJANGO_PROJECT_NAME}/neural_networks/ai_models:/home/heyot/web/neural_networks/ai_models
      - ./${DJANGO_PROJECT_NAME}/exported_tests_csv:/home/heyot/web/exported_tests_csv
      - sqlite_data:/home/${DJANGO_PROJECT_NAME}/web/sqlite_data
    ports:
      - 8000:8000
    env_file:
      - ./environment/.env.dev
######################################################################################
  mosquitto:
      container_name: ${DJANGO_PROJECT_NAME}_mosquitto
      image: ${DJANGO_PROJECT_NAME}_mosquitto
      build:
        context: ./mosquitto
        dockerfile: ./dockerfiles/Dockerfile
      hostname: mosquitto_broker
      volumes:
        - ./mosquitto/conf:/mosquitto/config
        - ./mosquitto/log:/mosquitto/log
        - ./mosquitto/data:/mosquitto/data
      restart: always
      ports:
          - 1883:1883
          - 5353:5353
      networks:
        - mosquitto
######################################################################################
networks:
  mosquitto:
    name: mosquitto
######################################################################################
volumes:
  sqlite_data:
