# Generated by Django 3.2.8 on 2023-11-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('message_uiid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('algo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_speed', models.FloatField(blank=True, null=True)),
                ('avg_latency', models.FloatField(blank=True, null=True)),
                ('inference_dev', models.CharField(blank=True, max_length=500, null=True)),
                ('inference_edge', models.CharField(blank=True, max_length=500, null=True)),
                ('chosen_offloading_layer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_loading_time', models.FloatField(blank=True, null=True)),
                ('update_time', models.FloatField(blank=True, null=True)),
                ('synt_load_edge', models.FloatField(blank=True, null=True)),
                ('synt_latency', models.FloatField(blank=True, null=True)),
                ('offloaded_layer_data_size', models.FloatField(blank=True, null=True)),
                ('layer_zero_data_size', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
